#!/bin/sh
set -e

remove() {
    printf "\033[32m Post Remove of a normal remove\033[0m\n"
    if command -V systemctl >/dev/null 2>&1; then
        do_systemd
    else
        do_initd
    fi
}

purge() {
    printf "\033[32m Post Remove purge, deb only\033[0m\n"
}

upgrade() {
    printf "\033[32m Post Remove of an upgrade\033[0m\n"
}

do_systemd() {
    # tedge-inventory
    systemctl disable tedge-inventory ||:
    if [ -d /run/systemd/system ]; then
        systemctl stop tedge-inventory ||:
    fi
}

do_initd() {
    service tedge-inventory stop ||:
}

action="$1"

case "$action" in
  "0" | "remove")
    remove
    ;;
  "1" | "upgrade")
    upgrade
    ;;
  "purge")
    purge
    ;;
  *)
    printf "\033[32m Alpine\033[0m"
    remove
    ;;
esac
